//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visualization.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AlphaOneDbContext : DbContext
    {
        public AlphaOneDbContext()
            : base("name=AlphaOneDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<access_level> access_level { get; set; }
        public virtual DbSet<arch> arches { get; set; }
        public virtual DbSet<architecture> architectures { get; set; }
        public virtual DbSet<iads_version> iads_version { get; set; }
        public virtual DbSet<IadsVersion> IadsVersions { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<project> projects { get; set; }
        public virtual DbSet<relate_type> relate_type { get; set; }
        public virtual DbSet<related_architecture> related_architecture { get; set; }
        public virtual DbSet<related_view> related_view { get; set; }
        public virtual DbSet<type> types { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<vw_architecture_product_in_dw> vw_architecture_product_in_dw { get; set; }
        public virtual DbSet<VW_Architecture_Viewer_Popup_Metadata> VW_Architecture_Viewer_Popup_Metadata { get; set; }
    }
}
