//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visualization.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IadsVersion
    {
        public int arch_id { get; set; }
        public int product_ID { get; set; }
        public string iads_version_name { get; set; }
        public Nullable<int> CAT_ARCH_ID { get; set; }
    }
}
