//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visualization.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int product_id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<bool> has_template { get; set; }
        public Nullable<System.DateTime> create_dttm { get; set; }
        public Nullable<int> create_user_id { get; set; }
        public Nullable<System.DateTime> updt_dttm { get; set; }
        public Nullable<int> updt_user_id { get; set; }
        public string short_description { get; set; }
        public Nullable<bool> is_active { get; set; }
        public bool is_dodaf_dw { get; set; }
        public Nullable<int> view_id { get; set; }
        public string iads_description { get; set; }
        public Nullable<bool> is_mission_thread_document_type { get; set; }
    }
}
