//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visualization.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class project
    {
        public int proj_id { get; set; }
        public string proj_nm { get; set; }
        public string proj_type_cd { get; set; }
        public Nullable<int> arch_cat_id { get; set; }
        public int sc_id { get; set; }
        public string sc_cd { get; set; }
        public string proj_short_nm { get; set; }
        public string proj_stat_cd { get; set; }
        public System.DateTime proj_stat_eff_dt { get; set; }
        public System.DateTime create_dttm { get; set; }
        public int create_user_id { get; set; }
        public System.DateTime updt_dttm { get; set; }
        public int updt_user_id { get; set; }
    }
}
