//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visualization.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.User1 = new HashSet<User>();
            this.User11 = new HashSet<User>();
        }
    
        public int Id { get; set; }
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FullName { get; set; }
        public string FullNameLastFirst { get; set; }
        public string EmailAddress { get; set; }
        public string PhoneNumber { get; set; }
        public string LocalDomainUserName { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime LastModified { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> SuspendedDate { get; set; }
        public string SuspenseJustification { get; set; }
        public Nullable<System.DateTime> SuspenseWarningEmailDate { get; set; }
        public Nullable<System.DateTime> SuspensedEmailDate { get; set; }
        public Nullable<bool> IsSuspensionManual { get; set; }
        public Nullable<System.DateTime> RobAcceptedDate { get; set; }
        public bool RobArCadie { get; set; }
        public bool RobMdTws { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> User1 { get; set; }
        public virtual User User2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> User11 { get; set; }
        public virtual User User3 { get; set; }
    }
}
