//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visualization.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_architecture_product_in_dw
    {
        public Nullable<int> cat_arch_id { get; set; }
        public int arch_id { get; set; }
        public string product_name { get; set; }
        public int product_id { get; set; }
        public string iads_version_name { get; set; }
        public int iads_version_id { get; set; }
    }
}
